### PR TITLE
Add Multilanguage Support and Chinese Language

### PR DESCRIPTION
**Pull request by awaysoft**

### CODE REVIEW

**Comment by felixinx** [comment]
Is this will be pushed in @daftspunk ?

**Comment by gabsource** [comment]
@daftspunk Is the multilingual support of the installer on the roadmap or the whishlist ?

**Comment by daftspunk** [comment]
Looks good for the most part, will take a look soon.

**Comment by daftspunk** [comment]
In general, this approach is good. There are some UI enhancements that are needed and this PR will be used to source the first language. Thanks for your patience as we work towards adding this.

**Comment by GinoPane** [comment]
@daftspunk Is this going to be released? Looks like it has been abandoned.

**Comment by LukeTowers** [comment]
@GinoPane it has been; for now at least. So many other things have come up since then. Feel free to take a stab at it yourself!

**Comment by daftspunk** [comment]
Installer in v2.0 has ML support

**Pull request closed without merging**
